### ISSUE TITLE
pages structure

### ISSUE THREAD

**Issue by hakase** [hakase/karasu#4]
Would like to be able to do:

```
pages:
- ['index.md', 'Home']
- ['anime.md', 'Anime']
- ['anime/bakemonogatari.md', 'Anime', 'Bakemonogatari']
```
mkdocs/mkdocs#6
ergonlogic/mkdocs@a1e06a1cd1fda5da5dc42015457f7f31e5d3bd92

**Comment by hakase** [comment]
```
Traceback (most recent call last):
  File "/home/lashni/dev/karasu/bin/mkdocs", line 9, in <module>
    load_entry_point('mkdocs==0.12.1', 'console_scripts', 'mkdocs')()
  File "/home/lashni/dev/karasu/src/mkdocs/mkdocs/main.py", line 77, in run_main
    main(cmd, args=sys.argv[2:], options=dict(opts))
  File "/home/lashni/dev/karasu/src/mkdocs/mkdocs/main.py", line 49, in main
    serve(config, options=options)
  File "/home/lashni/dev/karasu/src/mkdocs/mkdocs/serve.py", line 22, in serve
    builder()
  File "/home/lashni/dev/karasu/src/mkdocs/mkdocs/serve.py", line 19, in builder
    build(config, live_server=True)
  File "/home/lashni/dev/karasu/src/mkdocs/mkdocs/build.py", line 259, in build
    build_pages(config)
  File "/home/lashni/dev/karasu/src/mkdocs/mkdocs/build.py", line 216, in build_pages
    site_navigation = nav.SiteNavigation(config['pages'], config['use_directory_urls'])
  File "/home/lashni/dev/karasu/src/mkdocs/mkdocs/nav.py", line 37, in __init__
    _generate_site_navigation(pages_config, self.url_context, use_directory_urls)
  File "/home/lashni/dev/karasu/src/mkdocs/mkdocs/nav.py", line 250, in _generate_site_navigation
    header.children.append(page)
AttributeError: 'Page' object has no attribute 'children'
```

**Comment by hakase** [comment]
This works

```
pages:
- ['index.md', 'Home']
- ['anime.md', 'Anime', 'Anime']
- ['anime/bakemonogatari.md', 'Anime', 'Bakemonogatari']
- ['anime/ore-monogatari.md', 'Anime', 'Ore Monogatari']
- ['japan/travel.md', 'Japan', 'Travel']
```

```html
        <nav class="col-m-4">
          <ul>
          {% for nav_item in nav %}
            {% if nav_item.children %}
              {% if nav_item.title == nav_item.children[0].title %}
                <li><a href="{{ nav_item.children[0].url }}">{{ nav_item.children[0].title }}</a></li>
                <ul>
                {% for nav_item in nav_item.children %}
                  {% if not loop.first %}
                    <li><a href="{{ nav_item.url }}">{{ nav_item.title }}</a></li>
                  {% endif %}
                {% endfor %}
                </ul>
              {% else %}
                <li>{{ nav_item.title }}</li>
                <ul>
                {% for nav_item in nav_item.children %}
                  <li><a href="{{ nav_item.url }}">{{ nav_item.title }}</a></li>
                {% endfor %}
                </ul>
              {% endif %}
            {% else %}
              <li><a href="{{ nav_item.url }}">{{ nav_item.title }}</a></li>
            {% endif %}
          {% endfor %}
          </ul>
        </nav>
```
